# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcdb41b8f5bf4005d8e4537c75db0b3b39641d28db69379988ab116535ba73a967077913c85ef3673140e42b29d8bac9d58ae207fc35b9454acf2388fe21c895

test:
  secret_key_base: fbb587f758aee094d47d177fd5cb8e93f8723f7bf57a4807aa5178e5ef512c86bde3ddda15cb6394f793d5e6570b17e61be8131c9f1c4858153a36b43aac7ad8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
